services:
  app:
    build:
      context: .
      dockerfile: ./src/ELA.Api/Dockerfile
    image: ela-app:latest
    ports:
      - "8080:80"
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__ElaDb=Host=postgres-db;Port=5432;Database=ElaDb;Username=local_admin;Password=Secret123!
    restart: always

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: local_admin
      POSTGRES_PASSWORD: Secret123!
      POSTGRES_DB: ElaDb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
