version: '3.8'

services:
  app:
    image: app-image:latest
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./app:/app
    restart: always

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: local_admin
      POSTGRES_PASSWORD: Secret123!
      POSTGRES_DB: ElaDb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: